<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-03-09 09:01
=======
# Generated by Django 3.0 on 2020-03-08 19:14
>>>>>>> 41c076f5e789c660404cbbf5d3bb1a91e7f1edf3

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категорія блогу',
                'verbose_name_plural': 'Категорії блогу',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('post_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blog.PostCategory')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
    ]
