# Generated by Django 3.0.4 on 2020-03-16 08:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('img_alt', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Альт картинки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення')),
                ('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
            ],
            options={
                'verbose_name': 'Категорія блогу',
                'verbose_name_plural': 'Категорії блогу',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення')),
                ('img_alt', models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='Альт картинки')),
                ('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('post_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='blog.PostCategory', verbose_name='Відноситься до категорії')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
    ]
