# Generated by Django 3.0.3 on 2020-03-03 20:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('child_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='services.Country')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('count', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='countryservices',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='countryservices',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='countryservices',
            name='procedure',
        ),
        migrations.AddField(
            model_name='countryservices',
            name='slug',
            field=models.SlugField(default='5'),
        ),
        migrations.AlterField(
            model_name='countryservices',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_services', to='services.Country'),
        ),
        migrations.AddField(
            model_name='field',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='services.CountryServices'),
        ),
    ]
