# Generated by Django 3.0.3 on 2020-03-04 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycountry',
            name='child_country',
        ),
        migrations.AddField(
            model_name='country',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_country', to='services.CategoryCountry'),
        ),
    ]
