# Generated by Django 3.0.3 on 2020-03-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200304_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='category',
        ),
    ]
