# Generated by Django 3.0.3 on 2020-03-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_country_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='services.CategoryCountry'),
        ),
    ]
