# Generated by Django 3.0.3 on 2020-03-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_country_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='category',
        ),
        migrations.AddField(
            model_name='country',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='country', to='services.CategoryCountry'),
        ),
    ]
