# Generated by Django 3.0.3 on 2020-03-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20200304_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='countries', to='services.CategoryCountry'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='services.CountryServices'),
        ),
    ]
