# Generated by Django 3.0.3 on 2020-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20200304_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycountry',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='services.CountryServices'),
        ),
    ]
