# Generated by Django 3.0.3 on 2020-03-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20200304_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
