# Generated by Django 3.0.3 on 2020-03-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_categoryservices_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='services.CategoryServices'),
        ),
    ]
