# Generated by Django 3.0.3 on 2020-03-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20200304_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFieldAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
