# Generated by Django 3.0 on 2020-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_remove_country_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservices',
            options={'verbose_name': 'Сервіс із країнами', 'verbose_name_plural': 'Сервіси із країнами'},
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
