# Generated by Django 3.0 on 2020-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_auto_20200307_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycountry',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='countries', to='services.Country'),
        ),
    ]
