# Generated by Django 3.0 on 2020-03-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20200307_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorycountry',
            old_name='category',
            new_name='country',
        ),
    ]
