# Generated by Django 3.0 on 2020-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20200307_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycountry',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
