# Generated by Django 3.0.3 on 2020-03-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20200304_1044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='StaticService',
        ),
    ]
