# Generated by Django 3.0.3 on 2020-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20200304_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='category',
        ),
        migrations.AddField(
            model_name='categorycountry',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='services.CategoryCountry'),
        ),
    ]
