# Generated by Django 3.0.3 on 2020-03-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_categoryfieldadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryFieldAdmin',
        ),
    ]
