# Generated by Django 3.0.3 on 2020-03-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_delete_categoryfieldadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfield',
            name='title',
        ),
    ]
