# Generated by Django 3.0.3 on 2020-03-05 11:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_categoryfield_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservices',
            name='field',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryField',
        ),
    ]
