# Generated by Django 3.0 on 2020-03-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0021_auto_20200305_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(blank=True, null=True)),
                ('work_position', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_day', models.CharField(blank=True, max_length=1000, null=True)),
                ('our_duties', models.TextField(blank=True, null=True)),
                ('duties', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, related_name='categories', to='vacancy.Gender')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='services.Country')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vacancy.DocumetType')),
            ],
        ),
    ]
