# Generated by Django 3.0.4 on 2020-03-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Необхідні документи')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Опис необхідних документів')),
            ],
            options={
                'verbose_name': 'Необхідні документи',
                'verbose_name_plural': 'Необхідні документи',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_type', models.CharField(blank=True, max_length=100, null=True, verbose_name="Обов'язки")),
            ],
            options={
                'verbose_name': 'Робота для',
                'verbose_name_plural': 'Робота для',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип роботи')),
            ],
            options={
                'verbose_name': 'Тип роботи',
                'verbose_name_plural': 'Тип роботи',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва роботи')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Вимоги')),
                ('work_position', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адреса роботи')),
                ('work_day', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Графік роботи')),
                ('your_duties', models.TextField(blank=True, null=True, verbose_name='Витрати працівників')),
                ('our_duties', models.TextField(blank=True, null=True, verbose_name='Компанія надає')),
                ('duties', models.TextField(blank=True, null=True, verbose_name="Обов'язки")),
                ('actual', models.BooleanField(default=True, verbose_name='Актуальна?')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='service.Country', verbose_name='Країна')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vacancy.DocumetType', verbose_name='Необхідні документи')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.Gender', verbose_name='Робота для')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='vacancy.WorkType', verbose_name='Місце роботи')),
            ],
            options={
                'verbose_name': 'Вакансія',
                'verbose_name_plural': 'Вакансії',
            },
        ),
    ]
