# Generated by Django 3.0 on 2020-03-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200306_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documettype',
            options={'verbose_name': 'Тип документів', 'verbose_name_plural': 'Тип документів'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Стать', 'verbose_name_plural': 'Стать'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансія', 'verbose_name_plural': 'Вакансії'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Тип роботи', 'verbose_name_plural': 'Тип роботи'},
        ),
    ]
