# Generated by Django 3.0 on 2020-03-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20200307_1837'),
        ('vacancy', '0003_auto_20200307_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='genders', to='vacancy.Gender'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='services.Country'),
        ),
    ]
