# Generated by Django 3.0 on 2020-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_auto_20200307_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='actual',
            field=models.BooleanField(default=True),
        ),
    ]
