# Generated by Django 3.0 on 2020-03-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_vacancy_actual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documettype',
            options={'verbose_name': 'Тип документів', 'verbose_name_plural': 'Типи документів'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Тип роботи', 'verbose_name_plural': 'Типи роботи'},
        ),
    ]
