# Generated by Django 3.0 on 2020-03-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_auto_20200307_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
