# Generated by Django 3.0 on 2020-03-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_vacancy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='category',
            new_name='gender',
        ),
    ]
