# Generated by Django 3.0 on 2020-03-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_auto_20200307_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='your_duties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
